name: tag
on:
  push:
    branches: [main]
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - uses: Stefansm/nbgv.sh-action@test
        id: version
      - run: |
          git tag v${{ steps.version.outputs.version }}


