name: tag
on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml

  get-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - uses: Stefansm/nbgv.sh-action@test
        id: version
      - run: |
          git tag v${{ steps.version.outputs.version }}
      - run: |
          git push --tags


