name: test
run-name: Test pull request from ${{ github.actor }}
on:
  push:
    branches-ignore: [main]
  workflow_call: {}
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./test.sh
